### ISSUE TITLE
Pause Button Bug

### ISSUE THREAD

**Issue by SeaBa55** [AlecWGreene/MSU-Project3-Four-Horsemen#101]
The pause button is capable of sending waves when prior to game start.

**Comment by AlecWGreene** [comment]
So found the problem:

**File:** revelations/client/src/userInterface/components/GameContainer/index.js
 
 **Code:**
```JavaScript
   // Pause handler
    const handlePause = () => {
        if(state.runtimeState.isPaused){
            sfx.masterVolume(sfx.masterVol*4);
            state.manager.sendWave();
        }
        else{ 
            sfx.masterVolume(sfx.masterVol/4);
            state.manager.pause();
        }
    }
```

**Problem:** This method is being triggered everytime the pause button is clicked, and triggering pause state while the wave is not running shouldn't be an issue. The problem is that if the game is paused, the button will trigger `state.manager.sendWave()` which will force the manager to send the wave even if there is no wave running (which the game manager cannot differentiate between a call from the send wave button).

**Solution:** Add a conditional to check if a wave is currently running before making a call to sendWave.
